from read_data import train, test, mask
import numpy as np
import matplotlib.pyplot as plt
from Regression import Regression
from ACSM import ACSM
import itertools
from mpl_toolkits.mplot3d import Axes3D
import matplotlib as mpl
# *** item 1 ***
print("*** Item 1 ***")
print("Usando X=[carga] e y=[vo2max]")
X = np.array([[x] for x in train['carga']])
y = train['vo2max'].as_matrix()

X_test = np.asarray([[x] for x in test['carga']])
y_test = np.asarray(test['vo2max'])

degress = [1, 2, 3]
for d in degress:
	model = Regression(degree=d)
	W = model.fit(X, y)

	y_pred = model.predict(X_test)
	mse_error = model.mse_error(y_test, y_pred)
	score = model.score(y_test, y_pred)
	nll = model.NLL(X, y)

	print("grau " + str(d) + ": \n\tW = " + str([str(round(x, 5)) for x in W]) + "\n\tmse_error = " + str(mse_error) + "\n\tscore = " + str(score) + "\n\tNLL = " + str(nll))

	plt.cla()
	plt.title("Degree d = " + str(d))
	plt.ylabel('vo2max')
	plt.xlabel('carga')
	x_plot = [[x] for x in np.linspace(X.min(),X.max(),1000)]
	y_plot = model.predict(x_plot)

	pl1, = plt.plot(X, y, 'g.', label='Training data')
	pl2, = plt.plot(x_plot ,y_plot, 'b-', label='Function generated by W')
	plt.legend(handles=[pl1, pl2])
	plt.show()

# *** item 2 ***
print("*** Item 2 ***")
print("Usando X=[peso,carga] e y=[vo2max]")
X = train[['peso','carga']].as_matrix()
y = train['vo2max'].as_matrix()

X_test = test[['peso','carga']].as_matrix()
y_test = test['vo2max'].as_matrix()

degress = [1, 2, 3]
for d in degress:
	model = Regression(degree=d)
	# model.phi_inter = lambda X,d: [[1] + [x[0] , x[1], x[0]*x[1], x[0]**2, x[1]**2, x[0]*x[1]**2, x[1]*x[0]**2] for x in X]
	W = model.fit(X, y)

	y_pred = model.predict(X_test)
	mse_error = model.mse_error(y_test, y_pred)
	score = model.score(y_test, y_pred)
	nll = model.NLL(X, y)

	print("grau " + str(d) + ": \n\tW = " + str([str(round(x, 5)) for x in W]) + "\n\tmse_error = " + str(mse_error) + "\n\tscore = " + str(score) + "\n\tNLL = " + str(nll))

	plt3d = plt.figure().gca(projection='3d')
	x1_plot = np.linspace(X[:,0].min(),X[:,0].max(),10)
	x2_plot = np.linspace(X[:,1].min(),X[:,1].max(),10)

	xx, yy = np.meshgrid(x1_plot, x2_plot)
	z = list(itertools.product(x1_plot, x2_plot))
	zz = model.predict(z)
	zz = np.reshape(zz, (x2_plot.shape[0], x1_plot.shape[0]))

	plt3d.plot_surface(xx,yy,zz.transpose(), color='b')
	plt3d.plot(X[:,0],X[:,1],y, 'g.')
	plt3d.set_xlabel('peso')
	plt3d.set_ylabel('carga')
	plt3d.set_zlabel('vo2max')

	fake2Dline_train = mpl.lines.Line2D([0],[0], linestyle="none", c='b', marker = 'o')
	fake2Dline_func = mpl.lines.Line2D([0],[0], linestyle="none", c='g', marker = 'o')
	plt3d.legend([fake2Dline_train, fake2Dline_func], ['Function generated by W', 'Training data'], numpoints = 1)
	plt.show()


# *** item 3 ***
print("*** Item 3 ***")
print("Usando X=[peso,carga,idade] e y=[vo2max]")
X = train[['peso','carga','idade']].as_matrix()
y = train['vo2max'].as_matrix()

X_test = test[['peso','carga','idade']].as_matrix()
y_test = test['vo2max'].as_matrix()

degress = [1, 2, 3]
for d in degress:
	model = Regression(degree=d)
	W = model.fit(X, y)

	y_pred = model.predict(X_test)
	mse_error = model.mse_error(y_test, y_pred)
	score = model.score(y_test, y_pred)
	nll = model.NLL(X, y)

	print("grau " + str(d) + ": \n\tW = " + str([str(round(x, 5)) for x in W]) + "\n\tmse_error = " + str(mse_error) + "\n\tscore = " + str(score) + "\n\tNLL = " + str(nll))

# *** item 4 ***
print("*** Item 4 ***")
print("Usando X=[peso,carga] e y=[vo2max]")
X = train[['peso','carga']].as_matrix()
y = train['vo2max'].as_matrix()

X_test = test[['peso','carga']].as_matrix()
y_test = test['vo2max'].as_matrix()

model = ACSM()

y_pred = model.predict(X_test)
mse_error = model.mse_error(y_test, y_pred)
score = model.score(y_test, y_pred)

print("grau " + str(d) + ": \n\tmse_error = " + str(mse_error) + "\n\tscore = " + str(score))

plt3d = plt.figure().gca(projection='3d')
x1_plot = np.linspace(X[:,0].min(),X[:,0].max(),10)
x2_plot = np.linspace(X[:,1].min(),X[:,1].max(),10)

xx, yy = np.meshgrid(x1_plot, x2_plot)
z = list(itertools.product(x1_plot, x2_plot))
zz = model.predict(z)
zz = np.reshape(zz, (x2_plot.shape[0], x1_plot.shape[0]))

plt3d.plot_surface(xx,yy,zz.transpose(), color='b')
plt3d.plot(X[:,0],X[:,1],y, 'g.')
fake2Dline_train = mpl.lines.Line2D([0],[0], linestyle="none", c='b', marker = 'o')
fake2Dline_func = mpl.lines.Line2D([0],[0], linestyle="none", c='g', marker = 'o')
plt3d.legend([fake2Dline_train, fake2Dline_func], ['Function ACSM', 'Training data'], numpoints = 1)
plt3d.set_xlabel('peso')
plt3d.set_ylabel('carga')
plt3d.set_zlabel('vo2max')
plt.show()
