from read_data import train, test, mask
import numpy as np
import matplotlib.pyplot as plt
from Regression import Regression


# *** item 1 ***
print("*** Item 1 ***")
print("Usando X=[carga] e y=[vo2max]")
X = np.array([[x] for x in train['carga']])
y = train['vo2max'].as_matrix()

X_test = np.asarray([[x] for x in test['carga']])
y_test = np.asarray(test['vo2max'])

degress = [1, 2, 3]
for d in degress:
	model = Regression(degree=d)
	W = model.fit(X, y)
	
	y_pred = model.predict(X_test)
	mse_error = model.mse_error(y_test, y_pred)
	score = model.score(y_test, y_pred)

	print("grau " + str(d) + ": \n\tW = " + str([str(round(x, 5)) for x in W]) + "\n\tmse_error = " + str(mse_error) + "\n\tscore = " + str(score))

	plt.cla()
	plt.title("Degree d = " + str(d))
	plt.ylabel('vo2max')
	plt.xlabel('carga')
	x_plot = [[x] for x in np.linspace(X.min(),X.max(),1000)]
	y_plot = model.predict(x_plot)

	pl1, = plt.plot(X, y, 'g.', label='Training data')
	pl2, = plt.plot(x_plot ,y_plot, 'b-', label='Function generated by W')
	plt.legend(handles=[pl1, pl2])
	plt.show()

# *** item 2 ***
X = train[['peso','carga']].as_matrix()
y = train['vo2max'].as_matrix()

X_test = test[['peso','carga']].as_matrix()
y_test = test['vo2max'].as_matrix()

degress = [1, 2, 3]
for d in degress:
	model = Regression(degree=d)
	W = model.fit(X, y)
	
	y_pred = model.predict(X_test)
	mse_error = model.mse_error(y_test, y_pred)
	score = model.score(y_test, y_pred)

	print("grau " + str(d) + ": \n\tW = " + str([str(round(x, 5)) for x in W]) + "\n\tmse_error = " + str(mse_error) + "\n\tscore = " + str(score))

	# plt.cla()
	# plt.title("Degree d = " + str(d))
	# plt.ylabel('vo2max')
	# plt.xlabel('carga')
	# x_plot = [[x] for x in np.linspace(X.min(),X.max(),1000)]
	# y_plot = model.predict(x_plot)

	# pl1, = plt.plot(X, y, 'g.', label='Training data')
	# pl2, = plt.plot(x_plot ,y_plot, 'b-', label='Function generated by W')
	# plt.legend(handles=[pl1, pl2])
	# plt.show()